# Generated by Django 3.1.5 on 2021-05-09 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthenticationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_column='USER_NAME', max_length=35, verbose_name='User Name')),
                ('password', models.CharField(db_column='PASSWORD', max_length=35, verbose_name='Password')),
                ('created_on', models.DateTimeField(db_column='CREATED_DATE', verbose_name='Created On')),
            ],
            options={
                'db_table': 'REF_USER_AUTHENTICATION_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='UserSearchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_data', models.CharField(db_column='SEARCH_DATA', max_length=35, verbose_name='Search Data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_site.userauthenticationdetails')),
            ],
            options={
                'db_table': 'REF_USER_SEARCH_DATA',
            },
        ),
    ]
